"""Synthetic identity record model.

All records are fictional demonstration data generated by the seed script.
CNIC values use a Pakistan-style demo format but never reference real people.
"""

import enum
from datetime import date, datetime

from sqlalchemy import Date, DateTime, Enum, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base


class Gender(str, enum.Enum):
    MALE = "male"
    FEMALE = "female"


class IdentityStatus(str, enum.Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    UNDER_REVIEW = "under_review"


class IdentityRecord(Base):
    """A synthetic identity record, addressable only by exact CNIC lookup."""

    __tablename__ = "identity_records"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    cnic: Mapped[str] = mapped_column(String(15), unique=True, index=True, nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    father_name: Mapped[str] = mapped_column(String(120), nullable=False)
    date_of_birth: Mapped[date] = mapped_column(Date, nullable=False)
    gender: Mapped[Gender] = mapped_column(
        Enum(Gender, native_enum=False, length=10), nullable=False
    )
    address: Mapped[str] = mapped_column(String(255), nullable=False)
    photo_reference: Mapped[str | None] = mapped_column(String(255), nullable=True)
    status: Mapped[IdentityStatus] = mapped_column(
        Enum(IdentityStatus, native_enum=False, length=20),
        nullable=False,
        default=IdentityStatus.ACTIVE,
    )
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # One-to-one link to the synthetic reference DNA profile.
    dna_profile: Mapped["DnaProfile | None"] = relationship(  # noqa: F821
        back_populates="identity_record",
        uselist=False,
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<IdentityRecord cnic={self.cnic!r} name={self.name!r}>"
